name: Gitpoll notification2

on: [push]

jobs:
  caching-example:
    name: Caching
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment.yml') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: gitpoll
          channel-priority: strict
          environment-file: environment.yml
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!    - name: Run gitpoll
      - name: Cache gitpoll
        uses: actions/cache@v2
        with:
          path: |
            ~/gitpoll.s3db
      - shell: bash -l {0}
        run: |
          export JENKINS_USER=${{ secrets.JENKINS_USER }}
          export JENKINS_USER_ACCESS_TOKEN=${{ secrets.JENKINS_USER_ACCESS_TOKEN }}
          export PERSONNAL_GITHUB_ACCESS_TOKEN=${{ secrets.PERSONNAL_GITHUB_ACCESS_TOKEN }}
          python gitpoll.py gemoc.config
